# Agent configuration

# Agent descriptions for AI prompting and routing
agent_descriptions:
  listener: "Handles audio processing and speech recognition"
  translator: "Translates between languages"
  website_parser: "Searches websites for information"
  content_generator: "Creates multimedia content (images, videos, audio)"
  action_planner: "Breaks complex tasks into subtasks"
  mcp_searcher: "Finds relevant Model-Centric Processes"
  paralleliser: "Executes tasks in parallel"
  tool_finder: "Identifies relevant tools for user requests"
  orchestrator: "Routes requests to appropriate specialized agents"

agents:  
  # Listener agent configuration
  listener:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at processing and understanding audio content."
    language_detection: true
    speaker_diarization: false
    emotion_detection: false
    supported_formats:
      - wav
      - mp3
      - m4a
      - ogg
  
  # Translator agent configuration
  translator:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert translator who preserves context and meaning across languages."
    default_translation_engine: "openai"
    supported_languages:
      - en
      - es
      - fr
      - de
      - it
      - pt
      - ru
      - zh
      - ja
      - ko
  
  # Website Parser agent configuration
  website_parser:
    default_model: "claude-3-haiku"
    system_prompt: "You are an expert at finding and extracting relevant information from websites."
    max_pages: 5
    max_depth: 3
    relevance_threshold: 0.7
    respect_robots_txt: true
    timeout_seconds: 60
  
  # Orchestrator agent configuration
  orchestrator:
    default_model: "claude-3-5-haiku"
    system_prompt: "You are an expert at breaking complex tasks into well-defined subtasks."
    max_subtasks: 10
    planning_depth: 3
    min_subtask_size: 1
  
  # Content Generator agent configuration
  content_generator:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at creating high-quality content based on user specifications."
    supported_formats:
      - image
      - audio
      - video
      - diagram
    default_providers:
      image: "dalle3"
      audio: "elevenlabs"
      video: "runway"
      diagram: "mermaid"
  
  # MCP Searcher agent configuration
  mcp_searcher:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at finding and utilizing Model-Centric Processes (MCPs)."
  