# Default settings
default_model: phi4
log_level: INFO

# Use case specific configurations
use_cases:
  translation:
    quality: LOW
    speed: STANDARD
  coding:
    quality: HIGH
    speed: STANDARD
  solidity_coding:
    quality: HIGH
    speed: STANDARD
  chat:
    quality: MEDIUM
    speed: STANDARD
  content_generation:
    quality: MEDIUM
    speed: STANDARD
  data_analysis:
    quality: HIGH
    speed: SLOW
  web_analysis:
    quality: MEDIUM
    speed: SLOW
  image_generation:
    quality: HIGH
    speed: SLOW 